# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 但丁笔记
subtitle: #与细微处思寰宇，细思极恐
#description: dante's blog | IT | blog | 幽默 | 吐槽 | 兴趣爱好 | 折腾
description: 一个伪文青，一个low geek 孤单的坚持码字
author: 但丁
email: njhxzhangjihong@126.com
language: zh-Hans
timezone: 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://zhangjh.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: search/*.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: nextNew

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:zhangjh/myblog.git
  branch: gh-pages
  message: "add new pages"
  #type: git 
  #repo: git@gitcafe.com:JHspider/JHspider.git
  #branch: gitcafe-pages
  #message: "add new pages"

# Social links
social:
  github: https://github.com/zhangjh
  weibo: http://weibo.com/jhspider
  douban: http://douban.com/people/48165389
#  wechat: wechat.jpg

# rss feed
feed:
    type: rss2
    path: rss2.xml
    limit: 5
    hub:
    content: 'true'

# duoshuo评论
#duoshuo_shortname: zhangjh

#jiathis分享
jiathis: false

#友言评论
#youyan: true

# analytics
#baidu_analytics: 312d4ea056e663b0ca3a141dbd27f8fc
zhanzhang_analytics: yes

# site search
swiftype_key: kqk6Yx61eKS5JujMK_Zq
baidu_search: true
swiftype_search: false

# since
since: 2015

creative_commons: by-nc-sa

plugin:
- hexo-generator-sitemap

#sidebar
sidebar: post

#阅读全文
scroll_to_more: false

#为侧边栏文章的目录自动添加索引
toc_list_number: true 

google_site_verification: 4uI2zlyLHcOQWwwZFmW5SB6dj9mlInB8lIUfeM_L8d8
#baidu_union_verify: 6968173c085cc76d7ae38fb9af3c49ec
