<a rel="nofollow" target="_blank" href="http://union.click.jd.com/jdc?e=&p=AyIHZR5bEQMWDlwaWSUCGwZdGlodAREHZV8ETVxNNwxeHlQJDBkNXg9JHUlSSkkFSRwSDlQTWhQKEQRVBAJQXk83JxklRnV2YVN%2BCU1eSQYlHTpvXHd8NRdXJQcSAVcSXBAGEDdVGloUAxMFXBhcJTJzdWVaNRwBEwRSK14VCxMOVRpTFTISAlIcXBQBEwRQElgRMhU%3D&t=W1dCFBBFC1pXUwkEAEAdQFkJBVscAxoGVBNYFgINXhBHBg%3D%3D">JavaScript框架设计</a>
<script async>
	var books_links = [];
	var books_name = ["JavaScript编程实战","JavaScript设计模式","编写可维护的JavaScript","JavaScript框架设计","HTML5和JavaScript Web应用开发","网站设计项目化教程","Web前端开发案例教程","JavaScript面向对象精要","PHP.MySQL.JavaScript和CSS","JavaScript面向对象编程指南"];
	books_links.push("http://union.click.jd.com/jdc?e=&p=AyIHZR5bEQMWDlwaWSUCGwZdGlIXChYHZV8ETVxNNwxeHlQJDBkNXg9JHUlSSkkFSRwSDlQTWhwAGgNVBAJQXk83UWAzTAsMfyt5UhJGU3hWSEVdBERaJRdXJQcSAVcSXBAGEDdVGloUAxMFXBhcJTJzdWVaNRwBEwRSK14VCxMOVRpTFTISAlIcXBQCEAZVGlgTMhU%3D&t=W1dCFBBFC1pXUwkEAEAdQFkJBVscAxoGXBlTEQINXhBHBg%3D%3D");	
	books_links.push("http://union.click.jd.com/jdc?e=&p=AyIHZR5bEQMWDlwaWSUCEwZUG18QBRAPVSsfSlpMWGVCHlBDGRlLQx5BXg1cAAQJS14MB1QaWhUGFwBXE1sKW1dbCCsvFwdCeAwTAndKFVozYjx3WhYOAVMdGQ4iAlUdWRwFFwNXK1sUAxMGVBlSFgUiNzRpa1RsGwRUGFwlBxIOVBJbFAoSN1UeXBIFEwddGFIVCxs3Ug%3D%3D&t=W1dCFBBFC1pXUwkEAEAdQFkJBVsUAxMHUR5cFwoSGAxeB0g%3D");
	books_links.push("http://union.click.jd.com/jdc?e=&p=AyIHZR5bEQMWDlwaWSUCEwZUGFsTARIEXCsfSlpMWGVCHlBDGRlLQx5BXg1cAAQJS14MB1QaWhYCFARVGFIKW1dbCCslZnhsBABwLXYFSnsHRSFvClYOCEg7GQ4iAlUdWRwFFwNXK1sUAxMGVBlSFgUiNzRpa1RsGwRUGFwlBxIOVBJbFAoSN1UeXBIFEwddEl4XABM3Ug%3D%3D&t=W1dCFBBFC1pXUwkEAEAdQFkJBVsUAxMEVR1YFQEbGAxeB0g%3D");
	books_links.push("http://union.click.jd.com/jdc?e=&p=AyIHZR5bEQMWDlwaWSUCGwZdGlodAREHZV8ETVxNNwxeHlQJDBkNXg9JHUlSSkkFSRwSDlQTWhQKEQRVBAJQXk83JxklRnV2YVN%2BCU1eSQYlHTpvXHd8NRdXJQcSAVcSXBAGEDdVGloUAxMFXBhcJTJzdWVaNRwBEwRSK14VCxMOVRpTFTISAlIcXBQBEwRQElgRMhU%3D&t=W1dCFBBFC1pXUwkEAEAdQFkJBVscAxoGVBNYFgINXhBHBg%3D%3D");
	books_links.push("http://union.click.jd.com/jdc?e=&p=AyIHZR5bEQMWDlwaWSUCEwZUGVgSAhQOVCsfSlpMWGVCHlBDGRlLQx5BXg1cAAQJS14MB1QaWhcBFQdTEloKW1dbCCtSYXFQQShcAnZaTkMtWz1CWllaMlorGQ4iAlUdWRwFFwNXK1sUAxMGVBlSFgUiNzRpa1RsGwRUGFwlBxIOVBJbFAoSN1UeXBIFEwRVGlgUChs3Ug%3D%3D&t=W1dCFBBFC1pXUwkEAEAdQFkJBVsUAxMFVhxbEwsTGAxeB0g%3D");
	books_links.push("http://union.click.jd.com/jdc?e=&p=AyIHZR5bEQMWDlwaWSUCEwZUG1wVBxQPXSsfSlpMWGVCHlBDGRlLQx5BXg1cAAQJS14MB1QaWhUFEgJTE1MKW1dbCCsCFEoReg5cOHdbTm8PGxgUAnFyAUQdGQ4iAlUdWRwFFwNXK1sUAxMGVBlSFgUiNzRpa1RsGwRUGFwlBxIOVBJbFAoSN1UeXBIFEwRVGVgcCxQ3Ug%3D%3D&t=W1dCFBBFC1pXUwkEAEAdQFkJBVsUAxMHUhteEwoaGAxeB0g%3D");
	books_links.push("http://union.click.jd.com/jdc?e=&p=AyIHZR5bEQMWDlwaWSUCEwZUG14TBRQBVisfSlpMWGVCHlBDGRlLQx5BXg1cAAQJS14MB1QaWhUHFABTHVgKW1dbCCslXWBwRzFDBHBfSk40clNxY0dwPn8dGQ4iAlUdWRwFFwNXK1sUAxMGVBlSFgUiNzRpa1RsGwRUGFwlBxIOVBJbFAoSN1UeXBIFEwRWG1odBhU3Ug%3D%3D&t=W1dCFBBFC1pXUwkEAEAdQFkJBVsUAxMHUB1cEwQRGAxeB0g%3D");
	books_links.push("http://union.click.jd.com/jdc?e=&p=AyIHZR5aEwMaAlIaXyUCFQRWGVoUAxYHZV8ETVxNNwxeHlQJDBkNXg9JHUlSSkkFSRwSAFYYWRQDEwNVBAJQXk83T0NbRUlNcyZ4CBJqcH0LYwNcAmVPAxdXJQcSAVcSXBAGEDdVGloUAxMFXBhcJTJzdWVaNREHEw5cK14VCxMOVRpTFTISAlIcXBQBEQNUE1oUMhU%3D&t=W1dCFBBFC1pXUwkEAEAdQFkJBVsSAREFVBpaEQINXhBHBg%3D%3D");
	books_links.push("http://union.click.jd.com/jdc?e=&p=AyIHZR5aEwMaAlIaXyUCEgFcHFwRAREEZV8ETVxNNwxeHlQJDBkNXg9JHUlSSkkFSRwSB1MSXBIGEQRWBAJQXk83CRxBTHxsdwF%2BDF1CdHcXZw4WWWd6ExdXJQcSAVcSXBAGEDdVGloUAxMFXBhcJTJzdWVaNREHEw5cK14VCxMOVRpTFTISAlIcXBQBEQ5WE1MdMhU%3D&t=W1dCFBBFC1pXUwkEAEAdQFkJBVsVBBsAUh9YFgENXhBHBg%3D%3D");
	books_links.push("http://union.click.jd.com/jdc?e=&p=AyIHZR5aEwMaAlIaXyUCFw5RElgVAxsPZV8ETVxNNwxeHlQJDBkNXg9JHUlSSkkFSRwSAlwfUhYCEw5dBAJQXk83IEsAS2pSY1x%2BM1EYUEYDTw1VWUAdNRdXJQcSAVcSXBAGEDdVGloUAxMFXBhcJTJzdWVaNREHEw5cK14VCxMOVRpTFTISAlIcXBQBEAJUGlsWMhU%3D&t=W1dCFBBFC1pXUwkEAEAdQFkJBVsQCxYOVhtaHAoNXhBHBg%3D%3D");
	var content = "";
	var w = document.body.clientWidth,
		h = document.body.clientHeight;
	var len = books_links.length;
	if(w < h){
		len = 8;
	}
	for(var i=0;i<len;i++){
		content += "<a target='_blank' rel='nofollow' href='" + books_links[i] +  "'>" + books_name[i] +"</a>";
	}
	
	$("#recommendBooks").html(content);
</script> 
