{% if theme.zhanzhang_analytics %}
	<!--script src="http://s4.cnzz.com/stat.php?id=1255577055&web_id=1255577055" language="JavaScript"></script-->
	<script type="text/javascript">
		document.ready(function(){
			var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");
			document.write(unescape("%3Cspan style='display:none' id='cnzz_stat_icon_1255577055'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/stat.php%3Fid%3D1255577055%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));
		});
	</script>
{% endif %}
