{% if config.zhanzhang_analytics %}
	<!--script type="text/javascript" async>var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1255577055'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/stat.php%3Fid%3D1255577055%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));</script-->

	<span id='cnzz_stat_icon_1255577055'></span>
	<script src='//s4.cnzz.com/stat.php?id=1255577055&show=pic'></script>
{% endif %}
